TestApplication/Models/Education.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace TestApplication.Models
{
    public class Education
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Required")]
        [StringLength(100)]
        public string Title { get; set; }


        [Required(ErrorMessage = "Required")]
        [StringLength(75)]
        public string UniversityName { get; set; }

        [Required(ErrorMessage = "Required")]
        public DateTime DateOfGraduation { get; set; }


        public string Description { get; set; }

        public int UserId { get; set; }
    }
}

TestApplication/Models/ErrorViewModel.cs
using System;

namespace TestApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestApplication/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using TestApplication.Models;

namespace TestApplication.Models
{
    public class User
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Required")]
        [StringLength(25)]
        [Display(Name ="First Name")]
        [RegularExpression(@"^\S*$", ErrorMessage = "No white space allowed")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Required")]
        [StringLength(30)]
        [Display(Name = "Last Name")]
        [RegularExpression(@"^\S*$", ErrorMessage = "No white space allowed")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Required")]
        [StringLength(50)]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Required")]
        [RegularExpression("([0-9]+)", ErrorMessage = "Please enter valid Number")]
        [StringLength(20)]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Required")]
        [RegularExpression(@"^\S*$", ErrorMessage = "No white space allowed")]
        [StringLength(50)]
        public string Country { get; set; }


        [Display(Name = "Profile Picture")]
        public string ProfilePicture { get; set; }
        public string Hobbies { get; set; }

        public IEnumerable<Education> Educations { get; set; }

    }
}

TestApplication/ViewModels/UserFormViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestApplication.Models;

namespace TestApplication.ViewModels
{
    public class UserFormViewModel
    {
        public User User { get; set; }
        public IEnumerable<Education> Educations { get; set; }
    }
}

TestApplication/Controllers/Api/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestApplication.Models;
using TestApplication.ViewModels;


namespace TestApplication.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class UserController : ControllerBase
    {

        private static List<UserFormViewModel> _resLst = new List<UserFormViewModel>();


        [HttpPost]
        [Route("SaveToList")]
        public void SaveToList(UserFormViewModel userFormView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (userFormView != null)
                    {
                        var res = new UserFormViewModel { User = userFormView.User, Educations = userFormView.Educations };
                        addToList(res);
                    }
                }

            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }


        private void addToList(UserFormViewModel userFormView)
        {
            try
            {
                _resLst.Add(userFormView);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                throw;
            }
        }

    }
}

TestApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TestApplication.Models;
using TestApplication.Models;
using TestApplication.ViewModels;

namespace TestApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestApplication/Controllers/UserProfileController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestApplication.Models;
using TestApplication.ViewModels;

namespace TestApplication.Controllers
{
    public class UserProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult New()
        {
            var viewmodel = new UserFormViewModel {
                User = new User(),
                Educations = new List<Education>()
            };

            return View("UserForm",viewmodel);
        }

        public IActionResult Save()
        {
            return View();
        }
    }
}

TestApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TestApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TestApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    


</body>
</html>

TestApplication/Views/UserProfile/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "New User Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Users Profiles</h4>
<h5>@Html.ActionLink("Add new user", "New", "UserProfile")</h5>

TestApplication/Views/UserProfile/UserForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model TestApplication.ViewModels.UserFormViewModel
@{
    ViewBag.Title = "New User Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Add New User</h4>
@using (Html.BeginForm(new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true, "Please fix errors first")
    <div class="form-group" style="width:250px">
        @Html.LabelFor(x => x.User.FirstName)
        @Html.TextBoxFor(x => x.User.FirstName, new { @class = "form-control", id = "FirstName" })
        @Html.ValidationMessageFor(x => x.User.FirstName)

    </div>

    <div class="form-group" style="width:250px">
        @Html.LabelFor(x => x.User.LastName)
        @Html.TextBoxFor(x => x.User.LastName, new { @class = "form-control", id = "LastName" })
        @Html.ValidationMessageFor(x => x.User.LastName)
    </div>

    <div class="form-group" style="width:250px">
        @Html.LabelFor(x => x.User.Email)
        @Html.TextBoxFor(x => x.User.Email, new { @class = "form-control", id = "Email" })
        @Html.ValidationMessageFor(x => x.User.Email)
    </div>

    <div class="form-group" style="width:250px">
        @Html.LabelFor(x => x.User.Phone)
        @Html.TextBoxFor(x => x.User.Phone, new { @class = "form-control", id = "Phone" })
        @Html.ValidationMessageFor(x => x.User.Phone)
    </div>

    <div class="form-group" style="width:250px">
        @Html.LabelFor(x => x.User.Country)
        @Html.TextBoxFor(x => x.User.Country, new { @class = "form-control", id = "Country" })
        @Html.ValidationMessageFor(x => x.User.Country)
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.User.Hobbies)
        @Html.TextBoxFor(x => x.User.Hobbies, new { @class = "form-control", id = "Hobbies" })
        @Html.ValidationMessageFor(x => x.User.Hobbies)
    </div>

    <div>
        @Html.LabelFor(x => x.User.ProfilePicture)
        <input type="file" name="ImageData" id="ImageData" placeholder="Choose Profile Pic" />
    </div>



    <body>
        <table id="tblUsers" class="table" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th style="width:150px">Title</th>
                    <th style="width:150px">University Name</th>
                    <th style="width:150px">Date Of Graduation</th>
                    <th style="width:150px">Description</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @*@for (int i = 0; i < Model.Educations.Count(); i++)
                {
                    <tr>
                        
                        <td>
                            @Html.TextBoxFor(m => m.Educations.ToList()[i].Title, new { @class = "form-control", id = "txtTitle" })
                            @Html.ValidationMessageFor(m => m.Educations.ToList()[i].Title)
                        </td>
                        <td>
                            @Html.TextBoxFor(m => m.Educations.ToList()[i].UniversityName, new { @class = "form-control", id = "txtUniversityName" })
                            @Html.ValidationMessageFor(m => m.Educations.ToList()[i].UniversityName)
                        </td>
                        <td><input type="button" value="Remove" onclick="Remove(this)" /></td>
                    </tr>

                }*@


            </tbody>
            <tfoot>
                <tr>
                    <td><input type="text" id="txtTitle"  required /></td>
                    <td><input type="text" id="txtUniversityName"  required /></td>
                    <td><input type="date" id="txtDateOfGraduation" value=@DateTime.Now.ToShortDateString() min="1970-01-01" max=@DateTime.Now.ToShortDateString() required></td>
                    <td><input type="text" id="txtDescription" required /></td>
                    <td><input type="button" id="btnAdd" value="Add" /></td>
                </tr>
            </tfoot>
        </table>

        <button id="btnSave" class="btn btn-primary">Save</button>
    </body>

}


@section Scripts {

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript">

        var counter = 1;

        $("body").on("click", "#btnAdd", function () {

            
            if (counter <= 10) {
                //Reference the Name and Country TextBoxes.
                var txtTitle = $("#txtTitle");
                var txtUniversityName = $("#txtUniversityName");
                var txtDateOfGraduation = $("#txtDateOfGraduation");
                var txtDescription = $("#txtDescription");

                //Get the reference of the Table's TBODY element.
                var tBody = $("#tblUsers > TBODY")[0];

                //Add Row.
                var row = tBody.insertRow(-1);

                //Add Title cell.
                var cell = $(row.insertCell(-1));
                cell.html(txtTitle.val());
                txtTitle.attr("required",true)

                //Add University cell.
                cell = $(row.insertCell(-1));
                cell.html(txtUniversityName.val());
                txtUniversityName.attr("required", true)

                //Add DateOfGraduation cell.
                cell = $(row.insertCell(-1));
                cell.html(txtDateOfGraduation.val());
                txtDateOfGraduation.attr("required", true)
                txtDateOfGraduation.val();
                //Add Description cell.
                cell = $(row.insertCell(-1));
                cell.html(txtDescription.val());
               


                //Add Button cell.
                cell = $(row.insertCell(-1));
                var btnRemove = $("<input />");
                btnRemove.attr("type", "button");
                btnRemove.attr("onclick", "Remove(this);");
                btnRemove.val("Remove");
                cell.append(btnRemove);

                //Clear the TextBoxes.
                txtTitle.val("");
                txtUniversityName.val("");
                
                txtDescription.val("");

                counter++;
            }



        });

        function Remove(button) {
            //Determine the reference of the Row using the Button.
            var row = $(button).closest("TR");
            var name = $("TD", row).eq(0).html();
            if (confirm("Do you want to delete: " + name)) {
                //Get the reference of the Table.
                var table = $("#tblUsers")[0];

                //Delete the Table row using it's Index.
                table.deleteRow(row[0].rowIndex);

                counter--;
            }
        };


        $("body").on("click", "#btnSave", function () {

            var tmpVal = false;

            $("#tblUsers TBODY TR").each(function () {
                var row = $(this);
                
                var Title = row.find("TD").eq(0).html();
                var UniversityName = row.find("TD").eq(1).html();
                var DateOfGraduation = row.find("TD").eq(2).html();

                if (Title === '' || UniversityName === '') {
                    tmpVal = true;
                }
               
            });

            if (tmpVal) {
                return;
            }

            var user = {};

            user.FirstName = $("#FirstName").val();
            user.LastName = $("#LastName").val();
            user.Email = $("#Email").val();
            user.Phone = $("#Phone").val();
            user.Country = $("#Country").val();
            user.Hobbies = $("#Hobbies").val();
            user.ProfilePicture = $("#ImageData").val();

            //Loop through the Table rows and build a JSON array.
            var educations = new Array();
            $("#tblUsers TBODY TR").each(function () {
                var row = $(this);
                var education = {};
                education.Title = row.find("TD").eq(0).html();
                education.UniversityName = row.find("TD").eq(1).html();
                education.DateOfGraduation = row.find("TD").eq(2).html();
                education.Description = row.find("TD").eq(3).html();
                educations.push(education);
            });

            var userEducation = { User: user, Educations: educations };

            //Send the JSON array to Controller using AJAX.
            $.ajax({
                type: "POST",
                url: "https://localhost:44346/api/User/SaveToList",
                data: JSON.stringify(userEducation),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (res) {
                    alert('Operation Done !');
                },

                error: function (jqXHR, status) {
                    // error handler
                    console.log(jqXHR);
                    //alert('fail' + status.code);
                }
            });

           


        });


    </script>
}